
import os
import re
from io import BytesIO

# --- HELPER: SAFE UNICODE ---
def safe_encode(text):
    """
    Encodes text to latin-1 for FPDF compatibility, replacing unsupported chars.
    """
    replacements = {
        "’": "'", "‘": "'", "“": '"', "”": '"', "–": "-", "—": "-",
        "…": "...", "€": "EUR", "•": "*"
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode('latin-1', 'replace').decode('latin-1')

def create_pdf(text, filename="report.pdf"):
    """
    Generates a PDF from Markdown text using FPDF.
    Handles: Headers (#), Bullets (-), Bold (**).
    """
    try:
        from fpdf import FPDF
        
        class PDF(FPDF):
            def header(self):
                self.set_font('Arial', 'B', 15)
                self.cell(0, 10, 'Executive AI Report', 0, 1, 'C')
                self.ln(5)
            
            def footer(self):
                self.set_y(-15)
                self.set_font('Arial', 'I', 8)
                self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

        pdf = PDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # Cleanup Tags
        text = re.sub(r'\{\{.*?\}\}', '', text)
        
        lines = text.split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                pdf.ln(5)
                continue
            
            # 1. Headers
            if line.startswith('#'):
                level = len(line.split(' ')[0])
                clean_line = line.lstrip('#').strip()
                clean_line = safe_encode(clean_line)
                
                if level == 1:
                    pdf.set_font("Arial", 'B', 16)
                    pdf.ln(5)
                    pdf.multi_cell(0, 10, clean_line)
                    pdf.ln(2)
                elif level == 2:
                    pdf.set_font("Arial", 'B', 14)
                    pdf.ln(4)
                    pdf.multi_cell(0, 8, clean_line)
                    pdf.ln(1)
                else:         
                    pdf.set_font("Arial", 'B', 12)
                    pdf.multi_cell(0, 6, clean_line)
            
            # 2. Bullets
            elif line.startswith('- ') or line.startswith('* '):
                clean_line = line[2:].strip()
                clean_line = safe_encode(clean_line)
                pdf.set_font("Arial", '', 11)
                # Simple bullet using string concat
                pdf.multi_cell(0, 6, f"  * {clean_line}")
                
            # 3. Numbered Lists (1. )
            elif re.match(r'^\d+\.', line):
                clean_line = safe_encode(line)
                pdf.set_font("Arial", '', 11)
                pdf.multi_cell(0, 6, clean_line)
                
            # 4. Standard Text
            else:
                # Handle **Bold** replacement (naive)
                # FPDF standard doesn't support inline bold switch easily in multi_cell without HTMLMixin.
                # We will strip ** markers for cleaner look, or just keep them.
                # Let's strip them for professional look.
                line = line.replace('**', '').replace('__', '')
                clean_line = safe_encode(line)
                pdf.set_font("Arial", '', 11)
                pdf.multi_cell(0, 6, clean_line)
        
        # Output as bytes
        pdf_out = pdf.output(dest='S').encode('latin-1')
        return True, pdf_out, None
        
    except ImportError:
        return False, None, "Modulo 'fpdf' mancante. Installa con `pip install fpdf`."
    except Exception as e:
        return False, None, str(e)

def create_ppt_bytes(text, filename="report.pptx"):
    """
    Generates PPTX bytes, splitting slides by Headers.
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
        
        prs = Presentation()
        
        # --- TITLE SLIDE ---
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = "Executive SEO Report"
        subtitle.text = "Generated by AI Manager"
        
        # --- PARSING CONTENT ---
        # Cleanup
        text = re.sub(r'\{\{.*?\}\}', '', text)
        
        # Split by headers (Line starting with #, or 1. **)
        # We'll use a simple state machine.
        
        lines = text.split('\n')
        
        current_title = "Introduzione"
        current_body = []
        
        def add_content_slide(prs, title_str, body_lines):
            if not body_lines and not title_str: return
            
            layout = prs.slide_layouts[1] # Title + Content
            slide = prs.slides.add_slide(layout)
            
            # Title
            title = slide.shapes.title
            if title: title.text = title_str
            
            # Body
            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.word_wrap = True
            
            for line in body_lines:
                line = line.strip()
                if not line: continue
                
                p = tf.add_paragraph()
                p.text = line.replace('**', '') # Clean markers
                
                # Check for bullet
                if line.startswith('- ') or line.startswith('* '):
                    p.level = 1
                    p.text = line[2:].replace('**', '')
                elif re.match(r'^\d+\.', line):
                     p.level = 0
                else:
                     p.level = 0
                
                # Font size logic
                if len(body_lines) > 12:
                    p.font.size = Pt(14)
                else:
                    p.font.size = Pt(18)

        for line in lines:
            line = line.strip()
            if not line: continue
            
            # Detect Header (New Slide)
            if line.startswith('#'):
                # Save previous slide
                if current_body:
                    add_content_slide(prs, current_title, current_body)
                    current_body = []
                
                # Set new title
                clean_title = line.lstrip('#').strip()
                current_title = clean_title
            
            # Detect "1. **Title**" pattern often used in reports
            elif re.match(r'^\d+\.\s*\*\*', line):
                 # Save previous
                 if current_body:
                    add_content_slide(prs, current_title, current_body)
                    current_body = []
                 
                 # Extract title
                 current_title = line.replace('*', '')
            else:
                current_body.append(line)
        
        # Add last slide
        if current_body or current_title:
             add_content_slide(prs, current_title, current_body)

        out_ppt = BytesIO()
        prs.save(out_ppt)
        out_ppt.seek(0)
        return True, out_ppt, None
        
    except ImportError:
        return False, None, "Modulo 'python-pptx' mancante. Installa con `pip install python-pptx`."
    except Exception as e:
        return False, None, str(e)
